name: Trigger Render Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy
        run: |
          curl -X POST -f "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"